FROM node:20-alpine
    WORKDIR /app
    COPY package*.json ./
    RUN npm install --legacy-peer-deps
    COPY . .
    ENV NODE_ENV=production
    ENV PORT=3000
    RUN npm run build --if-present
    EXPOSE 3000
    CMD ["npm", "run", "start"]
    