version: '3.8'

services:
  agent-worker:
    profiles:
      - agents
    build:
      context: .
      dockerfile: Dockerfile.agent
    deploy:
      replicas: 1 # Scale this to set the number of parallel workers
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AGENT_WORKER_ID=docker-worker-{{.Task.Slot}}
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    volumes:
      - ./public/uploads:/app/public/uploads # Persist uploads
